DJANGO-LEVEL-4-LOGIN-AUTHENTICATION/catalog/urls.py
from django.urls import path
from catalog.views import CatalogHomeView, BookCreate, BookDetail, my_view, SignUpView, CheckedOutBooksByUser

urlpatterns = [
    path('', CatalogHomeView, name='catalog_home'),
    path('create_book/', BookCreate.as_view(), name='create_book'),
    path('book_detail/<slug:slug>/', BookDetail.as_view(), name='book_detail'),
    path('my_view/', my_view, name='my_view'),
    path('signup/', SignUpView.as_view(), name="sign_up"),
    path('profile/', CheckedOutBooksByUser.as_view(), name='profile'),    
]

DJANGO-LEVEL-4-LOGIN-AUTHENTICATION/libray/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')), # redirects domain.com ---->  domain.com/catalogue automatically using RedirectView.
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    
]

DJANGO-LEVEL-4-LOGIN-AUTHENTICATION/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from django.template.defaultfilters import slugify

import uuid
# Create your models here.
class Genre(models.Model):
    # model representing a book genre
    name = models.CharField(max_length=150)

    def __str__(self):
        return f'{self.name}'
    
class Language(models.Model):
    # model representing language of the book
    name = models.CharField(max_length=200)

    def __str__(self):
        return f'{self.name}'
    
class Book(models.Model):
    # model representing a book. 
    book_title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True) # This means if someone somehow accidently deletes the author, the book still exists, and author just returns NULL
    publish_date = models.DateField(auto_now=False, auto_now_add=True)
    summary = models.TextField(max_length=1000)
    isbn = models.CharField('ISBN', max_length=13, unique=True)
    genre = models.ManyToManyField(Genre) # book can have a list of potential genres
    language = models.ForeignKey('Language', on_delete=models.SET_NULL, null=True)
    
    def save(self, *args, **kwargs):
        #Generate slug based on title
        self.slug = slugify(self.book_title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.book_title}'
    
    def get_absolute_url(self):
        return reverse('book_detail', kwargs={'slug': self.slug})


class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    date_of_birth = models.DateField(auto_now=False, auto_now_add=False)

    class Meta: 
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        return reverse('author_detail', kwargs={'pk': self.pk})
    
    def __str__(self):
        return f'{self.first_name} {self.last_name}'
    
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(auto_now=False, auto_now_add=False, null=True)
    borrowed_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = [
        ('m', 'Maintenece'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved')    
    ]

    status = models.CharField(max_length=1,choices=LOAN_STATUS, blank=True, default='m')

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f'{self.id} ({self.book.book_title})'
    

DJANGO-LEVEL-4-LOGIN-AUTHENTICATION/catalog/views.py
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import CreateView, DetailView, ListView
from catalog.models import Book, Author, BookInstance, Genre,Language
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

# Create your views here.
def CatalogHomeView(request):

    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_avail = BookInstance.objects.filter(status__exact='a').count()
    
    context = {
        'num_books' : num_books,
        'num_instances' : num_instances,
        'num_instances_avail' : num_instances_avail,
    }

    return render(request, 'catalog/index.html', context=context)


class BookCreate(LoginRequiredMixin, CreateView): #For class based views, you need to use Mixins and pass it into the view.
    model = Book
    fields = ['book_title', 'author', 'summary', 'isbn','genre', 'language']
    
    def get_template_names(self):
        return ['catalog/book_form.html']
    
class BookDetail(DetailView):
    model = Book
    fields = "__all__"

    def get_object(self, queryset=None):
        # Retrieve the book based on the slug
        return get_object_or_404(Book, slug=self.kwargs['slug'])
    def get_template_names(self):
        return ['catalog/book_detail.html']

@login_required # Decorater that requires user to be auth'd before they can even view the page for a function based view.  
def my_view(request):
    return render(request='catalog/my_view.html')

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    
    def get_template_names(self):
        return ['catalog/sign_up.html']
    
class CheckedOutBooksByUser(LoginRequiredMixin, ListView):
    #List all BookInstances BUT i will filter based of currently logged in user session
    model = BookInstance
    paginate_by = 5 # how many Books per page. 

    def get_template_names(self):
        return ['catalog/profile.html']
    
    def get_queryset(self):
        return BookInstance.objects.filter(borrowed_by=self.request.user).order_by('due_back')#querey to be executed

DJANGO-LEVEL-4-LOGIN-AUTHENTICATION/templates/catalog/book_detail.html
{% extends "base.html" %}

{% block pagetitle %}{{book.book_title}}{% endblock pagetitle %}

{% block content %}
    {{book}}
    {{book.author}}
{% endblock content %}

DJANGO-LEVEL-4-LOGIN-AUTHENTICATION/templates/catalog/book_form.html
{% extends "base.html" %}

{% block pagetitle %}Create Book{% endblock pagetitle %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <P><input type="submit" value="Create Book"></P>
    </form>
{% endblock content %}
    

DJANGO-LEVEL-4-LOGIN-AUTHENTICATION/templates/catalog/index.html
{% extends 'base.html' %}

{% block pagetitle %}Catalog{% endblock pagetitle %}

{% block content %}
    <h1>Catalog Home View</h1>
    <p>Total number of books {{num_instances}}</p>
    {% if user.is_authenticated %}
        <p>Number of available books: {{num_instances_avail}}</p>
        <p>You are logged in!</p>
        <p>Welcome back {{user.get_username}}!</p>
        <form action="{% url 'logout' %}" method="POST">
            {% csrf_token %}
            <button class="btn-simple" type="submit">Logout</button>
        </form>
        {% else %}
        <p>You need to be logged in to view the available books!</p>
        <a href="{% url 'login' %}?next={{request.path}}">Login</a> <!-- {{request.path}} allows to be automatically redirected to the page where they clicked the link-->
        <a href="{% url 'sign_up' %}?next={{request.path}}">Sign Up</a>
    {% endif %}
{% endblock content %}

DJANGO-LEVEL-4-LOGIN-AUTHENTICATION/templates/catalog/my_view.html
{% extends "base.html" %}

{% block pagetitle %}My View{% endblock pagetitle %}

{% block content %}
    <h1>Logged in users only. </h1>
{% endblock content %}

DJANGO-LEVEL-4-LOGIN-AUTHENTICATION/templates/catalog/profile.html
{% extends "base.html" %}

{% block pagetitle %}{{user.get_username}}'s Profile{% endblock pagetitle %}

{% block content %}
    <p>Your current borrowed books!</p>
    <ul>
        {% for book in bookinstance_list %}
            <li><a href="/catalog/book_detail/{{book.book.slug}}/">{{book.book.book_title}}</a>, Written by {{book.book.author}}. </li>
                <ul>
                    <li>Due: {{book.due_back}}</li>
                </ul>
        {% empty %} <!--DEFAULT DJANGO TAG FOR LOOPS SPECIFICALLY WHEN A LOOP IN THIS INSTANCE A FOR LOOP IS EMPTY AND DOESN'T EXIST-->
            <p>You do not have any borrowed books</p>
        {% endfor %}
            
    </ul>

{% endblock content %}  

DJANGO-LEVEL-4-LOGIN-AUTHENTICATION/templates/catalog/sign_up.html
{% extends "base.html" %}

{% block pagetitle %}Sign Up{% endblock pagetitle %}

{% block content %}
    <h1>Register new user here.</h1>
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Sign Up">
    </form>
{% endblock content %}