DJANGO-LEVEL-3-DJANGO-ADMIN/car_sales/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("inventory_app.urls"))
]

DJANGO-LEVEL-3-DJANGO-ADMIN/django_admin/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

DJANGO-LEVEL-3-DJANGO-ADMIN/inventory_app/urls.py
from django.urls import path
from . import views

app_name = 'inventory_app'

urlpatterns = [
    path('',  views.list, name="list_cars"),
    path('delete/', views.delete, name="delete_cars"),
    path('add/', views.add, name="add_cars"),    
]

DJANGO-LEVEL-3-DJANGO-ADMIN/inventory_app/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    brand = models.CharField(max_length=30)
    year = models.IntegerField()

    def __str__(self):

        return f"Car is {self.brand} {self.year}"

DJANGO-LEVEL-3-DJANGO-ADMIN/inventory_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models

template_dir = 'inventory_app/'
# Create your views here.
def list(request):
    all_cars = models.Car.objects.all()
    context = {'all_cars':all_cars}
    return render(request, 'inventory_app/list.html', context = context)

def delete(request):
    if request.POST:
        pk = request.POST['pk']
        try:
            models.Car.objects.get(pk=pk).delete()
            print('car deleted!')
            return redirect(reverse('inventory_app:list_cars'))
            
        except:
            print('Car not found')
            return redirect(reverse('inventory_app:list_cars'))
    else:   
        return render(request, 'inventory_app/delete.html')

def add(request):
    if request.POST:
        brand = request.POST['brand']
        year = int(request.POST['year'])
        models.Car.objects.create(brand=brand, year=year)
        return redirect(reverse('inventory_app:list_cars'))
    else:
        return render(request, 'inventory_app/add.html')

DJANGO-LEVEL-3-DJANGO-ADMIN/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CAR SALES</title>
</head>
<body>

    <!--NAV BAR-->
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'inventory_app:list_cars'%}">LIST</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url "inventory_app:add_cars" %}">ADD</a>
              </li>
              <li class="navbar-item">
                <a class="nav-link" href="{% url "inventory_app:delete_cars" %}">DELETE</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

    {% block content %}
    
    {% endblock content %}


    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>