DJANGO-LEVEL-1-TEMPLATES/django_templates/django_templates/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),

]

handler404 = 'django_templates.views.my_custom_page_not_found_view'

DJANGO-LEVEL-1-TEMPLATES/django_templates/my_app/urls.py
from django.urls import path
from . import views


app_name = "my_app"

urlpatterns = [
    path('', views.example_view, name='example'), 
    path('variables/', views.example_variables, name='variable'),
]

DJANGO-LEVEL-1-TEMPLATES/django_templates/django_templates/views.py
from django.shortcuts import render



def my_custom_page_not_found_view(request, exception):

    return render (request, '404.html', status=404)

DJANGO-LEVEL-1-TEMPLATES/django_templates/my_app/views.py
from django.shortcuts import render

# Create your views here.
def example_view(request):
    # my_app/templates/my_app/example.hmtml
    return render(request, 'my_app/example.html')

def example_variables(request):
    my_var = {'first_name':'Rosalind', "last_name":"Franklin", 
              'some_list':[1,2,3], 'some_dict':{'inside_key' : 'outside_value'}}
    

    return render(request, 'my_app/variables.html', context=my_var)

DJANGO-LEVEL-1-TEMPLATES/django_templates/my_app/templates/my_app/example.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>THIS IS INSIDE THE BLOCK ON EXAMPLE.HTML</h1>
    <img src="{% static 'my_app/Django.jpg' %}" alt="my image">

{% endblock content %}

DJANGO-LEVEL-1-TEMPLATES/django_templates/my_app/templates/my_app/variables.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Variables Template DJANGO</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1>Variables & Tags In Django</h1>

        <p>Her first name was {{first_name}} her last name was {{last_name}}</p>
        {# THIS IS A COMMENT #}
        
        <ul>
            {% for item in some_list %}
                <li>{{item}}</li>
            {% endfor %}
        </ul>

        <ul>
            {% for k,v in some_dict.items %}
                <li>{{v}}</li>
                <li>{{k}}</li>
            {% endfor %}
        </ul>
        
        <script src="" async defer></script>
    </body>
</html>

DJANGO-LEVEL-1-TEMPLATES/django_templates/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Level 2 - Templates Base HTML</title>
</head>
<body>
    <h3><a href="{% url 'my_app:variable' %}">variable</a></h3>
    <h3><a href=" {% url 'my_app:example' %} ">Example</a></h3>
    <h1>THIS IS OUTSIDE THE BLOCK IN BASE.HTML</h1>
    {% block content %}
    


    {% endblock content %}
    <h2>THIS IS BELOW THE BLOCK IN BASE.HTML</h2>
    
</body>
</html>